# Generated by Django 2.1.7 on 2019-04-11 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0013_auto_20190410_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedbackType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('other_info', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='obj_feedbackType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedbackType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.feedbackType')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.Object')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='obj_feedbacktype',
            unique_together={('object', 'feedbackType')},
        ),
    ]
