# Generated by Django 2.1.7 on 2019-04-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0014_auto_20190411_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbacktype',
            name='other_info',
        ),
        migrations.AddField(
            model_name='obj_feedbacktype',
            name='other_info',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
