# Generated by Django 2.1.7 on 2019-04-12 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0015_auto_20190411_2055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='object',
            options={'ordering': ['id']},
        ),
    ]
