# Generated by Django 2.1.7 on 2019-05-22 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0016_auto_20190412_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tag',
            field=models.IntegerField(default=0),
        ),
    ]
